dependencies:
  easy_localization: ^3.0.5
  flutter:
    sdk: flutter
description: Library for internal ad localization.
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lingua_core: ^0.0.43
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
name: lingua_ad
repository: https://github.com/tyrcord/lingua/tree/main/packages/ad
version: 0.0.25
