name: lingua_ad
description: Library for internal ad localization.
version: 0.0.12
repository: https://github.com/tyrcord/lingua/tree/main/packages/ad

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  lingua_core: ^0.0.31
