name: lingua

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  update:scripts:
    exec: $PWD/scripts/copy.sh
  update:resources:
    exec: $PWD/scripts/update.sh
  generate:keys:
    exec: $PWD/scripts/generate.sh
  update:analysis_options:
    exec: $PWD/scripts/update_analysis_options.sh

ide:
  intellij:
    enabled: false
