name: lingua

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
  update:
    exec: $PWD/scripts/update.sh

  generate:
    exec: $PWD/scripts/generate.sh

ide:
  intellij:
    enabled: false
