name: lingua_finance_stock
description: Library for internal finance stock localization.
version: 0.0.6
repository: https://github.com/tyrcord/lingua/tree/main/packages/finance_stock

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  lingua_core: ^0.0.27
