dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
description: Library for internal finance stock localization.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lingua_core: ^0.0.45
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0 <4.0.0"
name: lingua_finance_stock
repository: https://github.com/tyrcord/lingua/tree/main/packages/finance_stock
version: 0.0.22
