include: package:flutter_lints/flutter.yaml
analyzer:
  language:
    strict-casts: true
linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_unused_constructor_parameters
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - constant_identifier_names
    - control_flow_in_finally
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - library_names
    - library_prefixes
    - collection_methods_unrelated_type
    - non_constant_identifier_names
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_final_fields
    - prefer_generic_function_type_aliases
    - prefer_is_not_empty
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unrelated_type_equality_checks
    - valid_regexps
    - use_super_parameters
    - use_to_and_as_if_applicable
    - use_setters_to_change_properties
    - use_enums
    - use_decorated_box
    - use_is_even_rather_than_modulo
    - use_colored_box
    - unnecessary_breaks
    - prefer_final_locals
    - prefer_final_in_for_each
    - unnecessary_await_in_return
    - cascade_invocations
