name: lingua_settings
description: Library for internal settings localization.
version: 0.0.12
repository: https://github.com/tyrcord/lingua/tree/main/packages/settings

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  lingua_core: ^0.0.31
