name: lingua_purchases
description: Library for internal purchases localization.
version: 0.0.13
repository: https://github.com/tyrcord/lingua/tree/main/packages/purchases

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.5
  lingua_core: ^0.0.21