name: lingua_finance_forex
description: Library for internal finance forex localization.
version: 0.0.1
repository: https://github.com/tyrcord/lingua/tree/main/packages/finance_forex

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.5
  lingua_core: ^0.0.2