name: lingua_finance_instrument
description: Library for internal finance instrument localization.
version: 0.0.2
repository: https://github.com/tyrcord/lingua/tree/main/packages/finance_instrument

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.5
  lingua_core: ^0.0.16