name: lingua_help
description: Library for internal help localization.
version: 0.0.10
repository: https://github.com/tyrcord/lingua/tree/main/packages/help

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  flutter_lints: ^3.0.1
  lingua_core: ^0.0.35
