dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
description: Library for internal help localization.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lingua_core: ^0.0.46
environment:
  flutter: '>=3.29.0 <4.0.0'
  sdk: '>=3.7.0 <4.0.0'
name: lingua_help
repository: https://github.com/tyrcord/lingua/tree/main/packages/help
version: 0.0.21
