name: lingua_core
description: Library for internal localization.
version: 0.0.1+2
repository: https://github.com/tyrcord/lingua/tree/main/packages/core

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.1
  args: ^2.3.1
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.5.0
