name: lingua_core
description: Library for internal localization.
version: 0.0.2
repository: https://github.com/tyrcord/lingua/tree/main/packages/core

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.1
  args: ^2.4.0
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.2
