name: lingua_core
description: Library for internal localization.
version: 0.0.18
repository: https://github.com/tyrcord/lingua/tree/main/packages/core

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.2
  args: ^2.4.0
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.5
