dependencies:
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  lingua_core: ^0.0.35
description: Library for internal numbers localization.
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
name: lingua_number
repository: https://github.com/tyrcord/lingua/tree/main/packages/number
version: 0.0.11
