dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  lingua_core: ^0.0.45
description: Library for internal numbers localization.
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: ">=3.24.0"
  sdk: ">=3.5.0 <4.0.0"
name: lingua_number
repository: https://github.com/tyrcord/lingua/tree/main/packages/number
version: 0.0.21
