name: Sort Imports

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sort_imports]
  schedule:
    - cron: "0 0 * * *"

env:
  changes: 0

jobs:
  sort-imports:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Set up Flutter environment
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      # Install Melos
      - name: Install and set Melos version
        uses: bluefireteam/melos-action@v3

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Sort imports
      - name: Sort imports
        run: melos run --no-select sort:imports

      # Check for any changes
      - name: Check for any changes
        id: git-check
        run: |
          git diff --exit-code -- '*.dart' || echo "changes=1" >> $GITHUB_ENV

      # Configure Git
      - name: Configure Git
        if: env.changes == '1'
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

      # Commit and push changes
      - name: Commit and push changes
        if: env.changes == '1'
        run: |
          git add -u *.dart
          git commit -m "chore: sorted imports"
          git push
