name: New versions

on:
  workflow_dispatch:
  repository_dispatch:
    types: [new_package_version]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Install Melos
      - name: Install and set Melos version
        uses: bluefireteam/melos-action@v3

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Code analysis
      - name: Analyze project source
        run: melos run --no-select analyze

      # Run tests
      - name: Run tests
        run: melos run --no-select test

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

      # Set package versions
      - name: Set package versions
        run: melos version --yes

      - name: Push tags
        run: git push --follow-tags
