name: Update packages versions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          # This is required to allow another workflow to be triggered
          token: ${{ secrets.WORKFLOW_TOKEN }}

      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      # Install Melos
      - name: Install and set Melos version
        uses: bluefireteam/melos-action@v3

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # melos bootstrap
      - name: Bootstrap
        run: melos bootstrap

      # Code analysis
      - name: Analyze project source
        run: melos run --no-select analyze

      # Run tests
      - name: Run tests
        run: melos run --no-select test

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

      # Set package versions
      - name: Set package versions
        run: melos version --yes

      # Create custom tag
      - name: Create custom tag
        run: |
          # Format the current date as yyyy-MM-dd
          TAG_DATE=$(date +%Y-%m-%d)
          # Create a custom tag
          CUSTOM_TAG="release-$TAG_DATE"
          echo "Creating and pushing tag $CUSTOM_TAG"
          # Create the tag
          git tag $CUSTOM_TAG

      # Push tags
      - name: Push tags
        run: git push --follow-tags
